import { Application } from "@/types";

declare global {
  // eslint-disable-next-line no-var
  var __mockApplicationsStore: Application[] | undefined;
}

if (!global.__mockApplicationsStore) {
  global.__mockApplicationsStore = [
    {
      id: "eth-app-701",
      first_name: "Dawit",
      middle_name: "Haile",
      last_name: "Tadesse",
      full_name: "Dawit Haile Tadesse",
      age: 26,
      full_address: "House 412, Woreda 03, Bole Sub-City, Addis Ababa, Ethiopia",
      phone: "+251 91 123 4567",
      email: "dawit.tadesse@aau.edu.et",
      qualification: "Bachelor's Degree (BA / BSc)",
      course_applied: "Job-Ready: Artificial Intelligence (AI)",
      signature: "Dawit H. Tadesse",
      place: "Addis Ababa",
      submission_date: "2026-08-28",
      status: "under_review",
      internal_notes: "FAYDA digital ID verified. Candidate completed BSc in Computer Science at AAU.",
      created_at: new Date(Date.now() - 3600000 * 36).toISOString(),
      updated_at: new Date(Date.now() - 3600000 * 12).toISOString(),
      files: [
        {
          id: "f-1",
          application_id: "eth-app-701",
          file_category: "fayda_id",
          file_path: "eth-app-701/fayda_national_id.pdf",
          file_name: "Official_Fayda_ID_Card.pdf",
          file_size: 1420000,
          mime_type: "application/pdf",
          uploaded_at: new Date(Date.now() - 3600000 * 36).toISOString(),
        },
        {
          id: "f-2",
          application_id: "eth-app-701",
          file_category: "payment_proof",
          file_path: "eth-app-701/cbe_transfer_receipt.jpg",
          file_name: "CBE_Birr_Payment_Slip.jpg",
          file_size: 980000,
          mime_type: "image/jpeg",
          uploaded_at: new Date(Date.now() - 3600000 * 18).toISOString(),
        },
      ],
    },
    {
      id: "eth-app-702",
      first_name: "Selamawit",
      middle_name: "Girma",
      last_name: "Bekele",
      full_name: "Selamawit Girma Bekele",
      age: 24,
      full_address: "Zone 2, Kebele 08, Hawassa, Sidama Region, Ethiopia",
      phone: "+251 92 345 6789",
      email: "selamawit.bekele@outlook.com",
      qualification: "Associate Degree / College Diploma",
      course_applied: "Job-Ready: Data Science and Big Data",
      signature: "Selamawit G.",
      place: "Hawassa",
      submission_date: "2026-08-29",
      status: "pending",
      internal_notes: undefined,
      created_at: new Date(Date.now() - 3600000 * 14).toISOString(),
      updated_at: new Date(Date.now() - 3600000 * 14).toISOString(),
      files: [
        {
          id: "f-3",
          application_id: "eth-app-702",
          file_category: "fayda_id",
          file_path: "eth-app-702/fayda_selam.png",
          file_name: "Fayda_Digital_Scan.png",
          file_size: 2100000,
          mime_type: "image/png",
          uploaded_at: new Date(Date.now() - 3600000 * 14).toISOString(),
        },
      ],
    },
    {
      id: "eth-app-703",
      first_name: "Yohannes",
      middle_name: "Kassaye",
      last_name: "Moges",
      full_name: "Yohannes Kassaye Moges",
      age: 31,
      full_address: "Sub-City Kirkos, Woreda 02, Addis Ababa, Ethiopia",
      phone: "+251 91 876 5432",
      email: "yohannes.kassaye@telecom.et",
      qualification: "Master's Degree (MA / MSc / MBA)",
      course_applied: "Job-Ready: Cloud Computing",
      signature: "Yohannes K. Moges",
      place: "Addis Ababa",
      submission_date: "2026-08-25",
      status: "approved",
      internal_notes: "Admitted with full scholarship subsidy. Percipio login assigned.",
      created_at: new Date(Date.now() - 3600000 * 72).toISOString(),
      updated_at: new Date(Date.now() - 3600000 * 20).toISOString(),
      files: [
        {
          id: "f-4",
          application_id: "eth-app-703",
          file_category: "fayda_id",
          file_path: "eth-app-703/fayda_doc.pdf",
          file_name: "Yohannes_Fayda_Identification.pdf",
          file_size: 1750000,
          mime_type: "application/pdf",
          uploaded_at: new Date(Date.now() - 3600000 * 72).toISOString(),
        },
        {
          id: "f-5",
          application_id: "eth-app-703",
          file_category: "payment_proof",
          file_path: "eth-app-703/cbe_slip.pdf",
          file_name: "Bank_Receipt_CBE_Deposit.pdf",
          file_size: 850000,
          mime_type: "application/pdf",
          uploaded_at: new Date(Date.now() - 3600000 * 60).toISOString(),
        },
      ],
    },
  ];
}

export const mockStore: Application[] = global.__mockApplicationsStore || [];
